compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@hmcts/playwright-common@*":
    dependencies:
      "@typescript-eslint/parser": ^8.8.0

yarnPath: .yarn/releases/yarn-4.11.0.cjs
