nodeLinker: node-modules

packageExtensions:
  "odhin-reports-playwright@*":
    dependencies:
      postcss: "^8.4.0"
  "@hmcts/playwright-common@*":
    dependencies:
      "@typescript-eslint/parser": "^8.54.0"
