export const EMPLOYMENT_ET_ENGLANDWALES_CASE_DATA: Record<string, unknown> = {
  jurCodesCollection: [
    {
      id: "f7f10b22-88c0-43b9-a917-f7fff81e006y",
      value: {
        juridictionCodesList: "DAG",
      },
    },
  ],
  typesOfClaim: ["discrimination"],
  positionType: "ET1 Online submission",
  conciliationTrack: "Open Track",
  receiptDate: "2019-08-17",
  feeGroupReference: "",
  managingOffice: "Newcastle",
  stateAPI: null,
  caseRefNumberCount: null,
  startCaseRefNumber: null,
  multipleRefNumber: null,
  caseType: "Single",
  multipleReference: null,
  leadClaimant: null,
  claimant_TypeOfClaimant: "Individual",
  claimant_Company: null,
  claimantIndType: {
    claimant_title1: "Dr",
    claimant_title_other: null,
    claimant_first_names: "Grayson",
    claimant_last_name: "Becker",
    claimant_date_of_birth: "1998-12-15",
    claimant_gender: "Male",
  },
  claimantType: {
    claimant_phone_number: null,
    claimant_mobile_number: null,
    claimant_email_address: null,
    claimant_contact_preference: null,
    claimant_addressUK: {
      AddressLine1: "4 Little Meadows",
      AddressLine2: "",
      AddressLine3: "",
      PostTown: "Bradley",
      County: "",
      Country: "United Kingdom",
      PostCode: "LL11 4AR",
    },
  },
  et1OnlineSubmission: "Yes",
  respondentCollection: [
    {
      value: {
        respondent_name: "Mrs Test Auto",
        respondent_ACAS_question: "Yes",
        respondent_ACAS: "R807115/23/89",
        respondent_ACAS_no: null,
        respondent_phone1: null,
        responseReceived: "No",
        responseContinue: null,
        responseReceivedDate: null,
        responseStruckOut: null,
        responseRespondentName: null,
        responseReference: null,
        response_status: null,
        responseToClaim: null,
        rejection_reason: null,
        rejection_reason_other: null,
        responseOutOfTime: null,
        responseNotOnPrescribedForm: null,
        responseRequiredInfoAbsent: null,
        responseStruckOutDate: null,
        responseStruckOutChairman: null,
        responseStruckOutReason: null,
        respondent_phone2: null,
        respondent_email: null,
        respondent_contact_preference: null,
        responseRespondentPhone1: null,
        responseRespondentPhone2: null,
        responseRespondentEmail: null,
        responseRespondentContactPreference: null,
        response_referred_to_judge: null,
        response_returned_from_judge: null,
        responseNotes: null,
        respondent_address: {
          AddressLine1: "78 East Wonford Hill",
          AddressLine2: "",
          AddressLine3: "",
          PostTown: "Exeter",
          County: "",
          Country: "United Kingdom",
          PostCode: "EX1 3DD",
        },
        responseRespondentAddress: {
          AddressLine1: null,
          AddressLine2: null,
          AddressLine3: null,
          PostTown: null,
          County: null,
          PostCode: null,
          Country: null,
        },
      },
      id: "e764f874-e937-4642-ac67-4af2e2fd05f6",
    },
  ],
  claimantWorkAddressQuestion: "No",
  claimantWorkAddress: {
    claimant_work_address: {
      Country: "United Kingdom",
      PostCode: "MK5 7HH",
      PostTown: "Milton Keynes",
      AddressLine1: "The Burnt Oak",
      AddressLine2: "Egerton Gate",
      AddressLine3: "Shenley Brook End",
    },
  },
  claimantWorkAddressQRespondent: {
    value: {
      code: "Mrs Test Auto",
      label:
        "Mrs Test Auto - 78 East Wonford Hill, Exeter, EX1 3DD, United Kingdom",
    },
    list_items: [
      {
        code: "Mrs Test Auto",
        label:
          "Mrs Test Auto - 78 East Wonford Hill, Exeter, EX1 3DD, United Kingdom",
      },
    ],
  },
  claimantOtherType: null,
  claimantRepresentedQuestion: "No",
  representativeClaimantType: null,
};
